### ISSUE TITLE
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:363 (message):   A required package was not found

### ISSUE THREAD

**Issue by shiptux** [slackwarecn-slackbuilds/fcitx-rime#3]
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:528 (_pkg_check_modules_internal)
  CMakeLists.txt:9 (pkg_check_modules)

-- Configuring incomplete, errors occurred!

**Comment by nnnewb** [comment]
missing dependencies.
please install [librime](https://github.com/slackwarecn-slackbuilds/librime) first.
